[38;21m2024-08-07 17:57:55,520 :: DEBUG :: icloudpy.base :: base.py :: 246 :: Using session file /tmp/icloudpy/runner/quentintarantinohotmailfr.session[0m
[38;5;39m2024-08-07 17:57:55,521 :: INFO :: icloudpy.base :: base.py :: 253 :: Session file does not exist[0m
[38;21m2024-08-07 17:57:55,521 :: DEBUG :: icloudpy.base :: base.py :: 318 :: Authenticating as quentintarantino@hotmail.fr[0m
[38;21m2024-08-07 17:57:55,521 :: DEBUG :: icloudpy.base :: base.py :: 350 :: Authentication completed successfully[0m
[38;21m2024-08-07 17:57:55,523 :: DEBUG :: root :: sync_drive.py :: 155 :: File /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/icloudpy/Test/Document scanne 2.pdf does not exist locally.[0m
[38;5;39m2024-08-07 17:57:55,523 :: INFO :: root :: sync_drive.py :: 203 :: Downloading /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/icloudpy/Test/Document scanne 2.pdf ...[0m
[38;21m2024-08-07 17:57:55,524 :: DEBUG :: root :: sync_drive.py :: 155 :: File /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/icloudpy/Test/Scanned document 1.pdf does not exist locally.[0m
[38;5;39m2024-08-07 17:57:55,524 :: INFO :: root :: sync_drive.py :: 203 :: Downloading /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/icloudpy/Test/Scanned document 1.pdf ...[0m
[38;21m2024-08-07 17:57:55,526 :: DEBUG :: root :: sync_drive.py :: 155 :: File /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/This is a title.md does not exist locally.[0m
[38;5;39m2024-08-07 17:57:55,526 :: INFO :: root :: sync_drive.py :: 203 :: Downloading /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/This is a title.md ...[0m
[38;21m2024-08-07 17:57:55,526 :: DEBUG :: root :: sync_drive.py :: 130 :: Package /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/Project.band does not exist locally.[0m
[38;5;39m2024-08-07 17:57:55,527 :: INFO :: root :: sync_drive.py :: 203 :: Downloading /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/Project.band ...[0m
[38;5;39m2024-08-07 17:57:55,528 :: INFO :: root :: sync_drive.py :: 166 :: Unpacking /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/Project.band.zip to /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample[0m
[38;5;39m2024-08-07 17:57:55,532 :: INFO :: root :: sync_drive.py :: 187 :: Successfully unpacked the package /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/Project.band.zip.[0m
[38;21m2024-08-07 17:57:55,533 :: DEBUG :: root :: sync_drive.py :: 130 :: Package /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/ms.band does not exist locally.[0m
[38;5;39m2024-08-07 17:57:55,533 :: INFO :: root :: sync_drive.py :: 203 :: Downloading /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/ms.band ...[0m
[38;5;39m2024-08-07 17:57:55,534 :: INFO :: root :: sync_drive.py :: 176 :: Unpacking /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/ms.band.gz to /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample[0m
[38;5;39m2024-08-07 17:57:55,536 :: INFO :: root :: sync_drive.py :: 166 :: Unpacking /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/ms.band.zip to /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample[0m
[38;5;39m2024-08-07 17:57:55,540 :: INFO :: root :: sync_drive.py :: 187 :: Successfully unpacked the package /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/ms.band.zip.[0m
[38;5;39m2024-08-07 17:57:55,540 :: INFO :: root :: sync_drive.py :: 187 :: Successfully unpacked the package /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/ms.band.gz.[0m
[38;21m2024-08-07 17:57:55,541 :: DEBUG :: root :: sync_drive.py :: 130 :: Package /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/FotoksiÄ…Å¼ka-WzÃ³r.xmcf does not exist locally.[0m
[38;5;39m2024-08-07 17:57:55,541 :: INFO :: root :: sync_drive.py :: 203 :: Downloading /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/FotoksiÄ…Å¼ka-WzÃ³r.xmcf ...[0m
[38;5;39m2024-08-07 17:57:55,542 :: INFO :: root :: sync_drive.py :: 166 :: Unpacking /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/FotoksiÄ…Å¼ka-WzÃ³r.xmcf.zip to /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample[0m
[38;5;39m2024-08-07 17:57:55,545 :: INFO :: root :: sync_drive.py :: 187 :: Successfully unpacked the package /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/FotoksiÄ…Å¼ka-WzÃ³r.xmcf.zip.[0m
