Loading config from /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/data/test_config.yaml ...
[38;21m2023-01-08 22:44:45,401 :: DEBUG :: icloudpy.base :: base.py :: 246 :: Using session file /tmp/icloudpy/runner/quentintarantinohotmailfr.session[0m
[38;5;39m2023-01-08 22:44:45,401 :: INFO :: icloudpy.base :: base.py :: 253 :: Session file does not exist[0m
[38;21m2023-01-08 22:44:45,402 :: DEBUG :: icloudpy.base :: base.py :: 318 :: Authenticating as quentintarantino@hotmail.fr[0m
[38;21m2023-01-08 22:44:45,402 :: DEBUG :: icloudpy.base :: base.py :: 350 :: Authentication completed successfully[0m
[38;21m2023-01-08 22:44:45,405 :: DEBUG :: root :: sync_drive.py :: 74 :: Skipping the unwanted folder /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Numbers ...[0m
[38;21m2023-01-08 22:44:45,406 :: DEBUG :: root :: sync_drive.py :: 74 :: Skipping the unwanted folder /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Pages ...[0m
[38;21m2023-01-08 22:44:45,407 :: DEBUG :: root :: sync_drive.py :: 74 :: Skipping the unwanted folder /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Preview ...[0m
[38;21m2023-01-08 22:44:45,409 :: DEBUG :: root :: sync_drive.py :: 132 :: File /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/icloudpy/Test/Document scanne 2.pdf does not exist locally.[0m
[38;5;39m2023-01-08 22:44:45,409 :: INFO :: root :: sync_drive.py :: 176 :: Downloading /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/icloudpy/Test/Document scanne 2.pdf ...[0m
[38;21m2023-01-08 22:44:45,410 :: DEBUG :: root :: sync_drive.py :: 132 :: File /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/icloudpy/Test/Scanned document 1.pdf does not exist locally.[0m
[38;5;39m2023-01-08 22:44:45,410 :: INFO :: root :: sync_drive.py :: 176 :: Downloading /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/icloudpy/Test/Scanned document 1.pdf ...[0m
[38;21m2023-01-08 22:44:45,411 :: DEBUG :: root :: sync_drive.py :: 74 :: Skipping the unwanted folder /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/unwanted ...[0m
[38;21m2023-01-08 22:44:45,414 :: DEBUG :: root :: sync_drive.py :: 132 :: File /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/This is a title.md does not exist locally.[0m
[38;5;39m2023-01-08 22:44:45,414 :: INFO :: root :: sync_drive.py :: 176 :: Downloading /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/This is a title.md ...[0m
[38;21m2023-01-08 22:44:45,415 :: DEBUG :: root :: sync_drive.py :: 107 :: Package /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/Project.band does not exist locally.[0m
[38;5;39m2023-01-08 22:44:45,415 :: INFO :: root :: sync_drive.py :: 176 :: Downloading /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/Project.band ...[0m
[38;5;39m2023-01-08 22:44:45,416 :: INFO :: root :: sync_drive.py :: 143 :: Unpacking /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/Project.band.zip to /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample[0m
[38;5;39m2023-01-08 22:44:45,421 :: INFO :: root :: sync_drive.py :: 160 :: Successfully unpacked the package /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/Project.band.zip.[0m
[38;21m2023-01-08 22:44:45,423 :: DEBUG :: root :: sync_drive.py :: 107 :: Package /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/ms.band does not exist locally.[0m
[38;5;39m2023-01-08 22:44:45,423 :: INFO :: root :: sync_drive.py :: 176 :: Downloading /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/ms.band ...[0m
[38;5;39m2023-01-08 22:44:45,425 :: INFO :: root :: sync_drive.py :: 149 :: Unpacking /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/ms.band.gz to /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample[0m
[38;5;39m2023-01-08 22:44:45,427 :: INFO :: root :: sync_drive.py :: 143 :: Unpacking /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/ms.band.zip to /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample[0m
[38;5;39m2023-01-08 22:44:45,431 :: INFO :: root :: sync_drive.py :: 160 :: Successfully unpacked the package /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/ms.band.zip.[0m
[38;5;39m2023-01-08 22:44:45,431 :: INFO :: root :: sync_drive.py :: 160 :: Successfully unpacked the package /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/ms.band.gz.[0m
[38;5;196m2023-01-08 22:44:45,432 :: ERROR :: root :: sync_drive.py :: 186 :: Failed to download /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/ms.band: [Errno 2] No such file or directory[0m
[38;5;39m2023-01-08 22:44:45,432 :: INFO :: root :: sync_drive.py :: 222 :: Removing /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/obsolete ...[0m
[38;5;39m2023-01-08 22:44:45,432 :: INFO :: root :: sync_drive.py :: 222 :: Removing /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/My Song.band ...[0m
