DEBUG    icloudpy.base:base.py:246 Using session file /tmp/icloudpy/runner/quentintarantinohotmailfr.session
INFO     icloudpy.base:base.py:253 Session file does not exist
DEBUG    icloudpy.base:base.py:318 Authenticating as quentintarantino@hotmail.fr
DEBUG    icloudpy.base:base.py:350 Authentication completed successfully
INFO     root:sync_drive.py:162 Downloading /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Scanned document 1.pdf ...
DEBUG    root:sync_drive.py:114 No changes detected. Skipping the file /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Scanned document 1.pdf ...
DEBUG    root:sync_drive.py:117 Changes detected: local_modified_time is 1662924366, remote_modified_time is 1588464917, local_file_size is 340532 and remote_file_size is 129525.
INFO     root:sync_drive.py:162 Downloading /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Scanned document 1.pdf ...