[38;21m2025-10-02 05:39:13,508 :: DEBUG :: icloudpy.base :: base.py :: 240 :: Using session file /tmp/icloudpy/runner/quentintarantinohotmailfr.session[0m
[38;5;39m2025-10-02 05:39:13,508 :: INFO :: icloudpy.base :: base.py :: 247 :: Session file does not exist[0m
[38;21m2025-10-02 05:39:13,509 :: DEBUG :: icloudpy.base :: base.py :: 313 :: Authenticating as quentintarantino@hotmail.fr[0m
[38;21m2025-10-02 05:39:13,517 :: DEBUG :: icloudpy.base :: base.py :: 417 :: Authentication completed successfully[0m
[38;21m2025-10-02 05:39:13,518 :: DEBUG :: root :: sync_photos.py :: 132 :: No changes detected. Skipping the file /home/runner/work/icloud-docker/icloud-docker/tests/temp/icloud/photos/test_photo__original__dGVzdF9waG90b19pZA==.jpg ...[0m
