[38;21m2025-09-19 04:01:45,028 :: DEBUG :: icloudpy.base :: base.py :: 240 :: Using session file /tmp/icloudpy/runner/quentintarantinohotmailfr.session[0m
[38;5;39m2025-09-19 04:01:45,028 :: INFO :: icloudpy.base :: base.py :: 247 :: Session file does not exist[0m
[38;21m2025-09-19 04:01:45,028 :: DEBUG :: icloudpy.base :: base.py :: 313 :: Authenticating as quentintarantino@hotmail.fr[0m
[38;21m2025-09-19 04:01:45,037 :: DEBUG :: icloudpy.base :: base.py :: 417 :: Authentication completed successfully[0m
[38;21m2025-09-19 04:01:45,040 :: DEBUG :: root :: config_parser.py :: 114 :: Checking root destination ...[0m
[38;21m2025-09-19 04:01:45,040 :: DEBUG :: icloudpy.base :: base.py :: 240 :: Using session file /config/session_data/quentintarantinohotmailfr.session[0m
[38;5;39m2025-09-19 04:01:45,040 :: INFO :: icloudpy.base :: base.py :: 247 :: Session file does not exist[0m
[38;21m2025-09-19 04:01:45,041 :: DEBUG :: icloudpy.base :: base.py :: 313 :: Authenticating as quentintarantino@hotmail.fr[0m
[38;21m2025-09-19 04:01:45,049 :: DEBUG :: icloudpy.base :: base.py :: 417 :: Authentication completed successfully[0m
[38;5;39m2025-09-19 04:01:45,049 :: INFO :: root :: sync.py :: 75 :: Syncing drive...[0m
[38;5;39m2025-09-19 04:01:45,049 :: INFO :: root :: sync.py :: 77 :: Drive synced[0m
[38;5;39m2025-09-19 04:01:45,049 :: INFO :: root :: config_parser.py :: 83 :: Syncing drive every 1 seconds.[0m
[38;5;39m2025-09-19 04:01:45,050 :: INFO :: root :: sync.py :: 80 :: Syncing photos...[0m
[38;5;39m2025-09-19 04:01:45,050 :: INFO :: root :: sync.py :: 82 :: Photos synced[0m
[38;5;39m2025-09-19 04:01:45,050 :: INFO :: root :: config_parser.py :: 98 :: Syncing photos every 2 seconds.[0m
[38;5;39m2025-09-19 04:01:45,050 :: INFO :: root :: sync.py :: 129 :: Resyncing at Fri Sep 19 04:01:46 2025 ...[0m
[38;5;39m2025-09-19 04:01:45,050 :: INFO :: root :: config_parser.py :: 83 :: Syncing drive every 1 seconds.[0m
[38;21m2025-09-19 04:01:45,050 :: DEBUG :: root :: config_parser.py :: 114 :: Checking root destination ...[0m
[38;21m2025-09-19 04:01:45,051 :: DEBUG :: icloudpy.base :: base.py :: 240 :: Using session file /config/session_data/quentintarantinohotmailfr.session[0m
[38;5;39m2025-09-19 04:01:45,051 :: INFO :: icloudpy.base :: base.py :: 247 :: Session file does not exist[0m
[38;21m2025-09-19 04:01:45,051 :: DEBUG :: icloudpy.base :: base.py :: 313 :: Authenticating as quentintarantino@hotmail.fr[0m
[38;21m2025-09-19 04:01:45,060 :: DEBUG :: icloudpy.base :: base.py :: 417 :: Authentication completed successfully[0m
[38;5;39m2025-09-19 04:01:45,060 :: INFO :: root :: sync.py :: 75 :: Syncing drive...[0m
[38;5;39m2025-09-19 04:01:45,060 :: INFO :: root :: sync.py :: 77 :: Drive synced[0m
[38;5;39m2025-09-19 04:01:45,060 :: INFO :: root :: config_parser.py :: 83 :: Syncing drive every 1 seconds.[0m
[38;5;39m2025-09-19 04:01:45,060 :: INFO :: root :: sync.py :: 129 :: Resyncing at Fri Sep 19 04:01:45 2025 ...[0m
[38;5;39m2025-09-19 04:01:45,060 :: INFO :: root :: config_parser.py :: 83 :: Syncing drive every 1 seconds.[0m
[38;21m2025-09-19 04:01:45,060 :: DEBUG :: root :: config_parser.py :: 114 :: Checking root destination ...[0m
[38;21m2025-09-19 04:01:45,061 :: DEBUG :: icloudpy.base :: base.py :: 240 :: Using session file /config/session_data/quentintarantinohotmailfr.session[0m
[38;5;39m2025-09-19 04:01:45,061 :: INFO :: icloudpy.base :: base.py :: 247 :: Session file does not exist[0m
[38;21m2025-09-19 04:01:45,061 :: DEBUG :: icloudpy.base :: base.py :: 313 :: Authenticating as quentintarantino@hotmail.fr[0m
[38;21m2025-09-19 04:01:45,070 :: DEBUG :: icloudpy.base :: base.py :: 417 :: Authentication completed successfully[0m
[38;5;39m2025-09-19 04:01:45,070 :: INFO :: root :: sync.py :: 75 :: Syncing drive...[0m
[38;5;39m2025-09-19 04:01:45,070 :: INFO :: root :: sync.py :: 77 :: Drive synced[0m
[38;5;39m2025-09-19 04:01:45,070 :: INFO :: root :: config_parser.py :: 83 :: Syncing drive every 1 seconds.[0m
[38;5;39m2025-09-19 04:01:45,070 :: INFO :: root :: sync.py :: 129 :: Resyncing at Fri Sep 19 04:01:46 2025 ...[0m
[38;5;39m2025-09-19 04:01:45,070 :: INFO :: root :: config_parser.py :: 83 :: Syncing drive every 1 seconds.[0m
[38;21m2025-09-19 04:01:45,070 :: DEBUG :: root :: config_parser.py :: 114 :: Checking root destination ...[0m
[38;21m2025-09-19 04:01:45,071 :: DEBUG :: icloudpy.base :: base.py :: 240 :: Using session file /config/session_data/quentintarantinohotmailfr.session[0m
[38;5;39m2025-09-19 04:01:45,071 :: INFO :: icloudpy.base :: base.py :: 247 :: Session file does not exist[0m
[38;21m2025-09-19 04:01:45,071 :: DEBUG :: icloudpy.base :: base.py :: 313 :: Authenticating as quentintarantino@hotmail.fr[0m
[38;21m2025-09-19 04:01:45,080 :: DEBUG :: icloudpy.base :: base.py :: 417 :: Authentication completed successfully[0m
[38;5;39m2025-09-19 04:01:45,080 :: INFO :: root :: sync.py :: 80 :: Syncing photos...[0m
[38;5;39m2025-09-19 04:01:45,080 :: INFO :: root :: sync.py :: 82 :: Photos synced[0m
[38;5;39m2025-09-19 04:01:45,080 :: INFO :: root :: config_parser.py :: 98 :: Syncing photos every 2 seconds.[0m
[38;5;39m2025-09-19 04:01:45,080 :: INFO :: root :: sync.py :: 129 :: Resyncing at Fri Sep 19 04:01:46 2025 ...[0m
[38;5;39m2025-09-19 04:01:45,081 :: INFO :: root :: config_parser.py :: 83 :: Syncing drive every 1 seconds.[0m
[38;21m2025-09-19 04:01:45,081 :: DEBUG :: root :: config_parser.py :: 114 :: Checking root destination ...[0m
[38;21m2025-09-19 04:01:45,081 :: DEBUG :: icloudpy.base :: base.py :: 240 :: Using session file /config/session_data/quentintarantinohotmailfr.session[0m
[38;5;39m2025-09-19 04:01:45,081 :: INFO :: icloudpy.base :: base.py :: 247 :: Session file does not exist[0m
[38;21m2025-09-19 04:01:45,082 :: DEBUG :: icloudpy.base :: base.py :: 313 :: Authenticating as quentintarantino@hotmail.fr[0m
[38;21m2025-09-19 04:01:45,090 :: DEBUG :: icloudpy.base :: base.py :: 417 :: Authentication completed successfully[0m
[38;5;39m2025-09-19 04:01:45,090 :: INFO :: root :: sync.py :: 75 :: Syncing drive...[0m
[38;5;39m2025-09-19 04:01:45,090 :: INFO :: root :: sync.py :: 77 :: Drive synced[0m
[38;5;39m2025-09-19 04:01:45,090 :: INFO :: root :: config_parser.py :: 83 :: Syncing drive every 1 seconds.[0m
[38;5;39m2025-09-19 04:01:45,091 :: INFO :: root :: sync.py :: 129 :: Resyncing at Fri Sep 19 04:01:45 2025 ...[0m
[38;5;39m2025-09-19 04:01:45,091 :: INFO :: root :: config_parser.py :: 83 :: Syncing drive every 1 seconds.[0m
[38;21m2025-09-19 04:01:45,091 :: DEBUG :: root :: config_parser.py :: 114 :: Checking root destination ...[0m
[38;21m2025-09-19 04:01:45,091 :: DEBUG :: icloudpy.base :: base.py :: 240 :: Using session file /config/session_data/quentintarantinohotmailfr.session[0m
[38;5;39m2025-09-19 04:01:45,091 :: INFO :: icloudpy.base :: base.py :: 247 :: Session file does not exist[0m
[38;21m2025-09-19 04:01:45,092 :: DEBUG :: icloudpy.base :: base.py :: 313 :: Authenticating as quentintarantino@hotmail.fr[0m
[38;21m2025-09-19 04:01:45,100 :: DEBUG :: icloudpy.base :: base.py :: 417 :: Authentication completed successfully[0m
[38;5;39m2025-09-19 04:01:45,100 :: INFO :: root :: sync.py :: 75 :: Syncing drive...[0m
[38;5;39m2025-09-19 04:01:45,100 :: INFO :: root :: sync.py :: 77 :: Drive synced[0m
[38;5;39m2025-09-19 04:01:45,101 :: INFO :: root :: config_parser.py :: 83 :: Syncing drive every 1 seconds.[0m
[38;5;39m2025-09-19 04:01:45,101 :: INFO :: root :: sync.py :: 129 :: Resyncing at Fri Sep 19 04:01:46 2025 ...[0m
[38;5;39m2025-09-19 04:01:45,101 :: INFO :: root :: config_parser.py :: 83 :: Syncing drive every 1 seconds.[0m
[38;21m2025-09-19 04:01:45,101 :: DEBUG :: root :: config_parser.py :: 114 :: Checking root destination ...[0m
[38;21m2025-09-19 04:01:45,101 :: DEBUG :: icloudpy.base :: base.py :: 240 :: Using session file /config/session_data/quentintarantinohotmailfr.session[0m
[38;5;39m2025-09-19 04:01:45,102 :: INFO :: icloudpy.base :: base.py :: 247 :: Session file does not exist[0m
[38;21m2025-09-19 04:01:45,102 :: DEBUG :: icloudpy.base :: base.py :: 313 :: Authenticating as quentintarantino@hotmail.fr[0m
[38;21m2025-09-19 04:01:45,110 :: DEBUG :: icloudpy.base :: base.py :: 417 :: Authentication completed successfully[0m
[38;5;39m2025-09-19 04:01:45,110 :: INFO :: root :: sync.py :: 80 :: Syncing photos...[0m
[38;5;39m2025-09-19 04:01:45,111 :: INFO :: root :: sync.py :: 82 :: Photos synced[0m
[38;5;39m2025-09-19 04:01:45,111 :: INFO :: root :: config_parser.py :: 98 :: Syncing photos every 2 seconds.[0m
[38;5;39m2025-09-19 04:01:45,111 :: INFO :: root :: sync.py :: 129 :: Resyncing at Fri Sep 19 04:01:46 2025 ...[0m
[38;5;39m2025-09-19 04:01:45,111 :: INFO :: root :: config_parser.py :: 83 :: Syncing drive every 1 seconds.[0m
[38;21m2025-09-19 04:01:45,111 :: DEBUG :: root :: config_parser.py :: 114 :: Checking root destination ...[0m
[38;21m2025-09-19 04:01:45,112 :: DEBUG :: icloudpy.base :: base.py :: 240 :: Using session file /config/session_data/quentintarantinohotmailfr.session[0m
[38;5;39m2025-09-19 04:01:45,112 :: INFO :: icloudpy.base :: base.py :: 247 :: Session file does not exist[0m
[38;21m2025-09-19 04:01:45,112 :: DEBUG :: icloudpy.base :: base.py :: 313 :: Authenticating as quentintarantino@hotmail.fr[0m
[38;21m2025-09-19 04:01:45,121 :: DEBUG :: icloudpy.base :: base.py :: 417 :: Authentication completed successfully[0m
[38;5;39m2025-09-19 04:01:45,121 :: INFO :: root :: sync.py :: 75 :: Syncing drive...[0m
[38;5;39m2025-09-19 04:01:45,121 :: INFO :: root :: sync.py :: 77 :: Drive synced[0m
[38;5;39m2025-09-19 04:01:45,121 :: INFO :: root :: config_parser.py :: 83 :: Syncing drive every 1 seconds.[0m
[38;5;39m2025-09-19 04:01:45,121 :: INFO :: root :: sync.py :: 129 :: Resyncing at Fri Sep 19 04:01:45 2025 ...[0m
[38;5;39m2025-09-19 04:01:45,121 :: INFO :: root :: config_parser.py :: 83 :: Syncing drive every 1 seconds.[0m
