Loading config from /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/data/test_config.yaml ...
[38;21m2023-03-16 16:28:50,371 :: DEBUG :: icloudpy.base :: base.py :: 246 :: Using session file /tmp/icloudpy/runner/quentintarantinohotmailfr.session[0m
[38;5;39m2023-03-16 16:28:50,371 :: INFO :: icloudpy.base :: base.py :: 253 :: Session file does not exist[0m
[38;21m2023-03-16 16:28:50,372 :: DEBUG :: icloudpy.base :: base.py :: 318 :: Authenticating as quentintarantino@hotmail.fr[0m
[38;21m2023-03-16 16:28:50,373 :: DEBUG :: icloudpy.base :: base.py :: 350 :: Authentication completed successfully[0m
[38;21m2023-03-16 16:28:50,374 :: DEBUG :: root :: sync_drive.py :: 24 :: Skipping the unwanted file /dir1/README.md[0m
[38;21m2023-03-16 16:28:50,375 :: DEBUG :: root :: sync_drive.py :: 24 :: Skipping the unwanted file /.git/index[0m
